const copy = {
  en: {
    teams: "Teams",
    globalFeed: "Global feed",
    close: "Close Teams",
    createTeam: "Create team",
    copyId: "Copy Your ID",
    copiedId: "Your ID was copied",
    copyFailed: "Could not copy your ID",
    teamName: "Team name",
    inviteTeammates: "Invite teammates",
    invite: "Invite",
    membersToInvite: "Members to invite",
    removeMember: "Remove member",
    invalidNpub: "Enter a valid npub",
    selfInvite: "You cannot invite yourself",
    duplicateMember: "This person is already on the team",
    nameRequired: "Enter a team name",
    memberRequired: "Invite at least one teammate",
    teamCreated: "Team created",
    membersAdded: "Members added",
    invitesSent: "Invitations sent",
    updateFailed: "Team update failed",
    myTeams: "My teams",
    emptyTeams: "You are not on a team yet. Create one to get started.",
    loadingTeams: "Loading teams…",
    loadFailed: "Could not load teams",
    progress: "Progress",
    memberLoadFailed: "Unable to load team members",
    noMembers: "No members yet",
    noProgress: "No published course progress yet",
    nameNotSet: "Name Not Set Yet",
    you: "you",
    creator: "Creator",
    member: "Member",
    memberCount: "members",
    memberCountSingular: "member",
    currentChapter: "Current chapter",
    noChapter: "No active chapter",
    chapterProgress: "Chapter progress",
    courseProgress: "Completion",
    goalCompletion: "Goal completion",
    dailyGoal: "Daily goal",
    noGoal: "No daily goal set",
    unavailable: "Unavailable",
    salary: "Salary",
    salaryPrivate: "Visible only to you",
    perYear: "per year",
    viewChapters: "View all chapters",
    hideChapters: "Hide chapters",
    questions: "questions",
    question: "question",
    complete: "complete",
    editName: "Edit team name",
    addMember: "Add new member",
    save: "Save",
    cancel: "Cancel",
    renamed: "Team renamed",
    deleteTeam: "Delete team",
    leaveTeam: "Leave team",
    deleted: "Team deleted",
    left: "You left the team",
    addressCopied: "Team address copied",
    syncFailed: "Course progress could not sync",
    feedLoading: "Syncing with the community…",
    feedFailed: "Could not load the global feed",
    feedEmpty: "No course updates yet",
    completedQuestion: "Completed question",
    refresh: "Refresh",
    chapter: "Chapter",
    of: "of",
    projected: "Projected annual value",
    pendingInvitations: "Pending invitations",
    invitedBy: "Invited by",
    accept: "Accept",
    decline: "Decline",
    accepted: "Invitation accepted",
    declined: "Invitation declined",
    inviteFailed: "Could not update invitation",
    confirmDelete: (name) => `Delete “${name}”?`,
    confirmLeave: (name) => `Leave “${name}”?`,
  },
  es: {
    teams: "Equipos",
    globalFeed: "Feed global",
    close: "Cerrar equipos",
    createTeam: "Crear equipo",
    copyId: "Copiar tu ID",
    copiedId: "Se copió tu ID",
    copyFailed: "No se pudo copiar tu ID",
    teamName: "Nombre del equipo",
    inviteTeammates: "Invitar compañeros",
    invite: "Invitar",
    membersToInvite: "Miembros para invitar",
    removeMember: "Eliminar miembro",
    invalidNpub: "Ingresa un npub válido",
    selfInvite: "No puedes invitarte a ti mismo",
    duplicateMember: "Esta persona ya está en el equipo",
    nameRequired: "Ingresa el nombre del equipo",
    memberRequired: "Invita al menos a una persona",
    teamCreated: "Equipo creado",
    membersAdded: "Miembros agregados",
    invitesSent: "Invitaciones enviadas",
    updateFailed: "No se pudo actualizar el equipo",
    myTeams: "Mis equipos",
    emptyTeams: "Aún no estás en un equipo. Crea uno para comenzar.",
    loadingTeams: "Cargando equipos…",
    loadFailed: "No se pudieron cargar los equipos",
    progress: "Progreso",
    memberLoadFailed: "No se pudieron cargar los miembros del equipo",
    noMembers: "Aún no hay miembros",
    noProgress: "Aún no hay progreso del curso publicado",
    nameNotSet: "Nombre aún no definido",
    you: "tú",
    creator: "Creador",
    member: "Miembro",
    memberCount: "miembros",
    memberCountSingular: "miembro",
    currentChapter: "Capítulo actual",
    noChapter: "Sin capítulo activo",
    chapterProgress: "Progreso del capítulo",
    courseProgress: "Finalización",
    goalCompletion: "Progreso de la meta",
    dailyGoal: "Meta diaria",
    noGoal: "Sin meta diaria",
    unavailable: "No disponible",
    salary: "Salario",
    salaryPrivate: "Visible solo para ti",
    perYear: "por año",
    viewChapters: "Ver todos los capítulos",
    hideChapters: "Ocultar capítulos",
    questions: "preguntas",
    question: "pregunta",
    complete: "completado",
    editName: "Editar nombre del equipo",
    addMember: "Agregar miembro",
    save: "Guardar",
    cancel: "Cancelar",
    renamed: "Equipo renombrado",
    deleteTeam: "Eliminar equipo",
    leaveTeam: "Salir del equipo",
    deleted: "Equipo eliminado",
    left: "Saliste del equipo",
    addressCopied: "Se copió la dirección del equipo",
    syncFailed: "No se pudo sincronizar el progreso del curso",
    feedLoading: "Sincronizando con la comunidad…",
    feedFailed: "No se pudo cargar el feed global",
    feedEmpty: "Aún no hay novedades del curso",
    completedQuestion: "Completó la pregunta",
    refresh: "Actualizar",
    chapter: "Capítulo",
    of: "de",
    projected: "Valor anual proyectado",
    pendingInvitations: "Invitaciones pendientes",
    invitedBy: "Invitado por",
    accept: "Aceptar",
    decline: "Rechazar",
    accepted: "Invitación aceptada",
    declined: "Invitación rechazada",
    inviteFailed: "No se pudo actualizar la invitación",
    confirmDelete: (name) => `¿Eliminar “${name}”?`,
    confirmLeave: (name) => `¿Salir de “${name}”?`,
  },
};
export const teamCopy = (language) =>
  copy[language?.startsWith("es") ? "es" : "en"];
